"""Render an emit_protocol payload to Markdown for export."""

from __future__ import annotations

from collections import Counter


def _cite(entry: dict) -> str:
    c = entry.get("citation")
    if not c:
        return ""
    ident = c.get("identifier", "")
    url = c.get("url") or (
        f"https://doi.org/{ident}" if ident.startswith("10.") else
        f"https://pubmed.ncbi.nlm.nih.gov/{ident}/" if ident.isdigit() else ""
    )
    label = f"{c.get('authors','')} {c.get('year','')} — {ident}".strip()
    link = f"[{label}]({url})" if url else label
    badge = " ✓ verified" if entry.get("citation_verified") else (
        " ⚠ unverified" if entry.get("provenance") == "literature_grounded" else ""
    )
    return f" ({link}{badge})"


def _tier(entry: dict) -> str:
    return f"`{entry.get('provenance', '')}`"


def protocol_to_markdown(p: dict) -> str:
    out: list[str] = []
    out.append(f"# {p.get('title', 'Protocol')}\n")
    if p.get("summary"):
        out.append(p["summary"] + "\n")
    if p.get("source_citation"):
        out.append(f"**Source:** {p['source_citation']}  ")
    if p.get("estimated_duration"):
        out.append(f"**Estimated duration:** {p['estimated_duration']}\n")

    # provenance summary
    tiers: Counter = Counter()
    for m in p.get("materials", []):
        tiers[m.get("provenance")] += 1
    for s in p.get("steps", []):
        tiers[s.get("provenance")] += 1
        for cp in s.get("critical_parameters", []):
            tiers[cp.get("provenance")] += 1
    rep = p.get("validation_report") or {}
    verified = len(rep.get("verified", []))
    downgraded = len(rep.get("downgraded", []))
    summary_bits = ", ".join(f"{v} {k}" for k, v in tiers.items() if k)
    out.append(f"> **Provenance:** {summary_bits}.")
    if rep:
        out.append(f"> **Citations:** {verified} verified, {downgraded} downgraded (unverifiable).\n")
    else:
        out.append("")

    mats = p.get("materials", [])
    if mats:
        out.append("## Materials\n")
        out.append("| Reagent | Amount | Grade/vendor | Provenance |")
        out.append("| --- | --- | --- | --- |")
        for m in mats:
            amt = " ".join(str(x) for x in [m.get("amount"), m.get("unit")] if x not in (None, ""))
            out.append(
                f"| {m.get('name','')} | {amt or '—'} | {m.get('vendor_or_grade') or '—'} | "
                f"{_tier(m)}{_cite(m)} |"
            )
        out.append("")

    if p.get("equipment"):
        out.append("## Equipment\n")
        for e in p["equipment"]:
            out.append(f"- {e}")
        out.append("")

    out.append("## Procedure\n")
    for s in p.get("steps", []):
        out.append(f"### {s.get('number')}. {s.get('title','')} {_tier(s)}\n")
        out.append(s.get("instruction", "") + "\n")
        meta = " · ".join(
            x for x in [
                f"⏱ {s.get('duration')}" if s.get("duration") else "",
                f"🌡 {s.get('temperature')}" if s.get("temperature") else "",
            ] if x
        )
        if meta:
            out.append(meta + "\n")
        for cp in s.get("critical_parameters", []):
            val = " ".join(str(x) for x in [cp.get("value"), cp.get("unit")] if x not in (None, ""))
            note = f" — {cp['provenance_note']}" if cp.get("provenance_note") else ""
            out.append(f"- **{cp.get('name','')}:** {val} {_tier(cp)}{_cite(cp)}{note}")
        for ss in s.get("substeps", []):
            out.append(f"  - {ss.get('number','')} {ss.get('instruction','')} {_tier(ss)}")
        for w in s.get("warnings", []):
            out.append(f"> ⚠ {w}")
        out.append("")

    alog = p.get("assumptions_log", [])
    if alog:
        out.append("## Assumptions log — everything not stated in the source\n")
        out.append("| Parameter | Value | Provenance | Basis |")
        out.append("| --- | --- | --- | --- |")
        for a in alog:
            verify = " · **verify**" if a.get("verify") else ""
            out.append(
                f"| {a.get('parameter','')} | {a.get('value','')} | {_tier(a)}{_cite(a)} | "
                f"{a.get('basis','')}{verify} |"
            )
        out.append("")

    if p.get("open_questions"):
        out.append("## Open questions\n")
        for q in p["open_questions"]:
            out.append(f"- {q}")
        out.append("")

    out.append("\n---\n*Generated by Methods Gap-Filler. Every value is provenance-tagged; "
               "`default_verify` items must be confirmed before use.*")
    return "\n".join(out)
