"""Render an emit_protocol payload to Markdown for export."""

from __future__ import annotations

from collections import Counter


def _safe_url(u: str) -> str:
    s = str(u or "").strip()
    return s if s.lower().startswith(("http://", "https://")) else ""


def _cite(entry: dict) -> str:
    c = entry.get("citation")
    if not c:
        return ""
    ident = c.get("identifier", "")
    url = _safe_url(c.get("url")) or (
        f"https://doi.org/{ident}" if ident.startswith("10.") else
        f"https://pubmed.ncbi.nlm.nih.gov/{ident}/" if ident.isdigit() else ""
    )
    label = f"{c.get('authors','')} {c.get('year','')} — {ident}".strip()
    link = f"[{label}]({url})" if url else label
    badge = " ✓ verified" if entry.get("citation_verified") else (
        " ⚠ unverified" if entry.get("provenance") == "literature_grounded" else ""
    )
    return f" ({link}{badge})"


def _tier(entry: dict) -> str:
    return f"`{entry.get('provenance', '')}`"


def protocol_to_markdown(p: dict) -> str:
    out: list[str] = []
    out.append(f"# {p.get('title', 'Protocol')}\n")
    if p.get("summary"):
        out.append(p["summary"] + "\n")
    if p.get("source_citation"):
        out.append(f"**Source:** {p['source_citation']}  ")
    if p.get("estimated_duration"):
        out.append(f"**Estimated duration:** {p['estimated_duration']}\n")

    # provenance summary
    tiers: Counter = Counter()
    for m in p.get("materials", []):
        tiers[m.get("provenance")] += 1
    for s in p.get("steps", []):
        tiers[s.get("provenance")] += 1
        for cp in s.get("critical_parameters", []):
            tiers[cp.get("provenance")] += 1
    rep = p.get("validation_report") or {}
    verified = len(rep.get("verified", []))
    downgraded = len(rep.get("downgraded", []))
    summary_bits = ", ".join(f"{v} {k}" for k, v in tiers.items() if k)
    out.append(f"> **Provenance:** {summary_bits}.")
    if rep:
        out.append(f"> **Citations:** {verified} verified, {downgraded} downgraded (unverifiable).\n")
    else:
        out.append("")

    mats = p.get("materials", [])
    if mats:
        out.append("## Materials\n")
        out.append("| Reagent | Amount | Grade/vendor | Provenance |")
        out.append("| --- | --- | --- | --- |")
        for m in mats:
            amt = " ".join(str(x) for x in [m.get("amount"), m.get("unit")] if x not in (None, ""))
            out.append(
                f"| {m.get('name','')} | {amt or '—'} | {m.get('vendor_or_grade') or '—'} | "
                f"{_tier(m)}{_cite(m)} |"
            )
        out.append("")

    if p.get("equipment"):
        out.append("## Equipment\n")
        for e in p["equipment"]:
            out.append(f"- {e}")
        out.append("")

    out.append("## Procedure\n")
    for s in p.get("steps", []):
        out.append(f"### {s.get('number')}. {s.get('title','')} {_tier(s)}\n")
        out.append(s.get("instruction", "") + "\n")
        meta = " · ".join(
            x for x in [
                f"⏱ {s.get('duration')}" if s.get("duration") else "",
                f"🌡 {s.get('temperature')}" if s.get("temperature") else "",
            ] if x
        )
        if meta:
            out.append(meta + "\n")
        for cp in s.get("critical_parameters", []):
            val = " ".join(str(x) for x in [cp.get("value"), cp.get("unit")] if x not in (None, ""))
            note = f" — {cp['provenance_note']}" if cp.get("provenance_note") else ""
            out.append(f"- **{cp.get('name','')}:** {val} {_tier(cp)}{_cite(cp)}{note}")
        for ss in s.get("substeps", []):
            out.append(f"  - {ss.get('number','')} {ss.get('instruction','')} {_tier(ss)}")
        for w in s.get("warnings", []):
            out.append(f"> ⚠ {w}")
        out.append("")

    alog = p.get("assumptions_log", [])
    if alog:
        out.append("## Assumptions log — everything not stated in the source\n")
        out.append("| Parameter | Value | Provenance | Basis |")
        out.append("| --- | --- | --- | --- |")
        for a in alog:
            verify = " · **verify**" if a.get("verify") else ""
            out.append(
                f"| {a.get('parameter','')} | {a.get('value','')} | {_tier(a)}{_cite(a)} | "
                f"{a.get('basis','')}{verify} |"
            )
        out.append("")

    if p.get("open_questions"):
        out.append("## Open questions\n")
        for q in p["open_questions"]:
            out.append(f"- {q}")
        out.append("")

    out.append("\n---\n*Generated by Methods Gap-Filler. Every value is provenance-tagged; "
               "`default_verify` items must be confirmed before use.*")
    return "\n".join(out)


_VERDICT_LABEL = {"yes": "✓ Directly tests the hypothesis",
                  "partial": "◐ Partially tests the hypothesis",
                  "no": "✗ Does not directly test the hypothesis"}


def design_alignment_to_markdown(a: dict) -> str:
    out: list[str] = ["# Does this test your hypothesis?\n"]
    h = a.get("hypothesis") or {}
    if h.get("statement"):
        tag = " *(inferred)*" if a.get("inferred") else ""
        out.append(f"**Hypothesis{tag}:** {h['statement']}")
        if h.get("prediction_if_true"):
            out.append(f"- If true → {h['prediction_if_true']}")
        if h.get("prediction_if_false"):
            out.append(f"- If false → {h['prediction_if_false']}")
        out.append("")

    dt = a.get("directly_tests") or {}
    if dt:
        out.append(f"**Verdict:** {_VERDICT_LABEL.get(dt.get('verdict'), dt.get('verdict',''))}")
        if dt.get("rationale"):
            out.append(f"> {dt['rationale']}")
        out.append("")

    if a.get("critical_comparison"):
        out.append(f"**The comparison that makes it a valid test:** {a['critical_comparison']}\n")

    gaps = a.get("alignment_gaps") or []
    if gaps:
        out.append("## Where it falls short of testing the hypothesis\n")
        for g in gaps:
            out.append(f"- **{g.get('gap','')}** — {g.get('why_it_breaks_the_test','')}")
        out.append("")

    conf = a.get("confounds") or []
    if conf:
        out.append("## Confounds that would make a positive result ambiguous\n")
        for c in conf:
            mit = f" *Mitigation:* {c['mitigation']}" if c.get("mitigation") else ""
            out.append(f"- **{c.get('confound','')}** — {c.get('makes_result_ambiguous','')}.{mit}")
        out.append("")

    rc = a.get("recommended_changes") or []
    if rc:
        out.append("## Recommended protocol changes (to make it a direct test)\n")
        for c in rc:
            out.append(f"- **[{c.get('type','change')}]** {c.get('change','')}  \n"
                       f"  *Addresses:* {c.get('addresses','')}")
        out.append("")

    if a.get("summary"):
        out.append(f"**Bottom line:** {a['summary']}")
    return "\n".join(out)


def design_review_to_markdown(d: dict) -> str:
    out: list[str] = ["# Experiment design review\n"]
    if d.get("question"):
        out.append(f"**Question:** {d['question']}\n")
    if d.get("hypothesis"):
        out.append(f"**Hypothesis:** {d['hypothesis']}\n")

    v = d.get("variables") or {}
    if v:
        out.append("## Variables\n")
        for k in ("independent", "dependent", "controlled"):
            vals = v.get(k) or []
            out.append(f"- **{k.capitalize()}:** {', '.join(vals) if vals else '—'}")
        out.append("")

    controls = d.get("controls") or []
    if controls:
        out.append("## Controls — and what each rules out\n")
        out.append("| Control | Type | Rules out | Provenance |")
        out.append("| --- | --- | --- | --- |")
        for c in controls:
            out.append(
                f"| {c.get('name','')} | {c.get('type','')} | {c.get('rules_out','')} | "
                f"{_tier(c)}{_cite(c)} |"
            )
        out.append("")

    r = d.get("readout") or {}
    if r:
        out.append("## Readout adequacy\n")
        ok = "✓ tests the hypothesis" if r.get("answers_question") else "⚠ may not test the hypothesis"
        out.append(f"Measures: {r.get('measures','')} — **{ok}**.")
        if r.get("caveat"):
            out.append(f"> Caveat: {r['caveat']}")
        out.append("")

    rep = d.get("replication") or {}
    if rep:
        out.append("## Replication\n")
        bio = rep.get("biological"); tech = rep.get("technical")
        if bio:
            out.append(f"- Biological replicates: {bio}")
        if tech:
            out.append(f"- Technical replicates: {tech}")
        out.append(f"- Rationale: {rep.get('rationale','')}\n")

    er = d.get("expected_results") or []
    if er:
        out.append("## Expected results — if you see X, it means Y\n")
        for e in er:
            out.append(f"- **{e.get('scenario','')}** → {e.get('interpretation','')}")
        out.append("")

    fm = d.get("failure_modes") or []
    if fm:
        out.append("## Failure modes\n")
        out.append("| Symptom | Likely cause | Check |")
        out.append("| --- | --- | --- |")
        for f in fm:
            out.append(f"| {f.get('symptom','')} | {f.get('likely_cause','')} | {f.get('check') or '—'} |")
        out.append("")

    lim = d.get("interpretation_limits") or []
    if lim:
        out.append("## What this experiment cannot conclude\n")
        for x in lim:
            out.append(f"- {x}")
        out.append("")

    gaps = d.get("design_gaps") or []
    if gaps:
        out.append("## Design gaps to fix in this plan\n")
        for g in gaps:
            out.append(f"- {g}")
        out.append("")

    return "\n".join(out)
